version: '3'
services:
  nestjs:
    image: andrevaleriounc/nestjs-server:1.0
    restart: always
    ports:
      - "3000:3000"
    networks:
      - mysql-net
    environment:
      - DATABASE_URL=mysql://root:root@mysql-master:3306/m1_to_do_list
    pull_policy: always

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 60
    restart: always

networks:
  mysql-net:
    external: true